### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vishu2048**
Fixed a spelling mistake. I'm not sure whether it was intentional or not

### CODE REVIEW

**Comment by taufik-nurrohman** [comment]
Did you replace `&rsquo;` with `'`?

**Comment by Vishu2048** [comment]
Yeah, was it intentional ?

**Comment by taufik-nurrohman** [comment]
Yes. It&rsquo;s called HTML entity. And was added to make fancy quote. See below comparison:

 - It's
 - I&rsquo;s

**Comment by Vishu2048** [comment]
Oh, sorry I didn't know about html entities

**Comment by taufik-nurrohman** [comment]
It&rsquo;s okay. That&rsquo;s a good start to contribute to open-source 👍

**Pull request closed without merging**
