### PR TITLE
Update color-picker.js

### PR DESCRIPTION
**Pull request by cxF9Au4t**
Hello,

Many thanks for this Color Picker. I'm using it in a browser extension for Firefox. I have noticed that there is a warning about innerHTML during the validation of the extension. I have already replaced it on my site, but you might want to add it in case others want to use it in browser extensions as well.

https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

### CODE REVIEW

**Comment by taufik-nurrohman** [comment]
I will merge your change first, but will reference the DOM directly to variable `C`, `SV`, `H`, etc. later, so no need to re-assign to those variables. Thanks.

**Review by taufik-nurrohman — APPROVED** [review]
Thanks.

**Comment by cxF9Au4t** [comment]
The warning has gone. Thanks :+1:

A small donation is on the way :wink:

**Comment by taufik-nurrohman** [comment]
Thank you.

**Pull request merged**
